import type { TrainingPuzzle } from '../training-types';

export interface TacticalPuzzleItem extends TrainingPuzzle {
  readonly elo: number;
  readonly theme: 'fork' | 'pin' | 'mate-in-1' | 'mate-in-2' | 'discovered-attack' | 'win-material' | 'endgame';
}

export const OFFLINE_TACTICS_PACK: readonly TacticalPuzzleItem[] = [
  // --- MATE EN 1 (Principiante ELO 800 - 1100) ---
  {
    id: 'off-m1-01',
    title: 'Beso de la Muerte',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 1,
    elo: 850,
    rewardXp: 15,
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 4',
    solution: [{ from: 'f3', to: 'f7' }],
    objective: 'Dar jaque mate en una sola jugada aprovechando la debilidad en f7.',
    explanation: 'Dxf7# remata la partida gracias al apoyo del alfil en c4.',
    alternative: 'Controla siempre el punto f7 en aperturas abiertas.',
  },
  {
    id: 'off-m1-02',
    title: 'Mate del Pasillo Clásico',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 1,
    elo: 900,
    rewardXp: 15,
    fen: '6k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: [{ from: 'd1', to: 'd8' }],
    objective: 'Aprovechar la falta de escape del rey en la octava fila.',
    explanation: 'Td8# aprovecha que los propios peones negros bloquean a su rey.',
    alternative: 'Crea siempre un respiradero (luft) como h6 o g6 en tus partidas.',
  },
  {
    id: 'off-m1-03',
    title: 'Mate del Pastor Invertido',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 1,
    elo: 880,
    rewardXp: 15,
    fen: 'r1b1k1nr/pppp1ppp/2n5/2b1p3/4P2q/3P1N2/PPP2PPP/RNBQKB1R b KQkq - 2 4',
    solution: [{ from: 'h4', to: 'f2' }],
    objective: 'Castigar el descuido en la casilla f2.',
    explanation: 'Dxf2# remata aprovechando la cobertura del alfil en c5.',
    alternative: 'La casilla f2/f7 es la más vulnerable antes del enroque.',
  },
  {
    id: 'off-m1-04',
    title: 'Mate de la Coz Inmediato',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 2,
    elo: 1050,
    rewardXp: 20,
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: [{ from: 'h6', to: 'f7' }],
    objective: 'Dar jaque mate de caballo contra un rey asfixiado.',
    explanation: 'Cf7# explota que la torre y los peones negros encierran a su propio rey.',
    alternative: 'El caballo salta sobre cualquier bloqueo.',
  },
  {
    id: 'off-m1-05',
    title: 'Mate Anastasiano en Octava',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 2,
    elo: 1100,
    rewardXp: 20,
    fen: '5rk1/5ppp/8/8/8/5N2/1R6/6K1 w - - 0 1',
    solution: [{ from: 'b2', to: 'b8' }],
    objective: 'Entrar en la octava fila para dar mate.',
    explanation: 'Tb8 clava y elimina cualquier defensa en la última línea.',
    alternative: 'Las torres dobladas o en séptima/octava deciden partidas.',
  },
  {
    id: 'off-m1-06',
    title: 'Mate con Dos Torres (Escalera)',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 1,
    elo: 800,
    rewardXp: 15,
    fen: '7k/R7/8/8/8/8/1R6/6K1 w - - 0 1',
    solution: [{ from: 'b2', to: 'b8' }],
    objective: 'Ejecutar el corte definitivo de la escalera.',
    explanation: 'Tb8# corta la última fila mientras Ta7 controla la séptima.',
    alternative: 'El mate de la escalera es el patrón básico de torres.',
  },
  {
    id: 'off-m1-07',
    title: 'Mate de Dama y Rey en la Banda',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 1,
    elo: 820,
    rewardXp: 15,
    fen: 'k7/8/1K6/8/8/8/8/1Q6 w - - 0 1',
    solution: [{ from: 'b1', to: 'b7' }],
    objective: 'Cerrar la red de mate contra el rey arrinconado.',
    explanation: 'Db7# apoyada por el rey blanco termina la partida.',
    alternative: 'Acerca tu rey para apoyar a tu dama.',
  },
  {
    id: 'off-m1-08',
    title: 'Mate de los Dos Alfiles',
    category: 'mate-in-1',
    theme: 'mate-in-1',
    difficulty: 2,
    elo: 1080,
    rewardXp: 20,
    fen: 'k7/8/1KB5/8/8/8/1B6/8 w - - 0 1',
    solution: [{ from: 'b2', to: 'd4' }],
    objective: 'Coordinar la pareja de alfiles para dar mate en la esquina.',
    explanation: 'Ad4# cubre la diagonal final contra el rey rival.',
    alternative: 'La pareja de alfiles cubre diagonales adyacentes de forma letal.',
  },

  // --- TENEDOR / HORQUILLA (Principiante e Intermedio ELO 950 - 1500) ---
  {
    id: 'off-fork-01',
    title: 'Horquilla Real de Caballo',
    category: 'basic-tactics',
    theme: 'fork',
    difficulty: 2,
    elo: 1150,
    rewardXp: 20,
    fen: 'r3k3/8/8/8/8/5N2/8/4K3 w q - 0 1',
    solution: [{ from: 'f3', to: 'e5' }],
    objective: 'Crear un doble ataque contra el rey y la torre.',
    explanation: 'Ce5+ da jaque y captura la torre indefensa en la siguiente jugada.',
    alternative: 'Busca siempre casillas donde el caballo alcance 2 objetivos de valor.',
  },
  {
    id: 'off-fork-02',
    title: 'Tenedor Central de Peón',
    category: 'win-material',
    theme: 'fork',
    difficulty: 2,
    elo: 1200,
    rewardXp: 20,
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/1bB1n3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5',
    solution: [{ from: 'd2', to: 'd4' }],
    objective: 'Avanzar el peón central para amenazar dos piezas menores a la vez.',
    explanation: 'd4 ataca al alfil en b4 y al caballo/peón central ganando una pieza.',
    alternative: 'Los peones que avanzan dos pasos en el centro rompen esquemas tácticos.',
  },
  {
    id: 'off-fork-03',
    title: 'Horquilla en c7 con Ganancia de Torre',
    category: 'win-material',
    theme: 'fork',
    difficulty: 2,
    elo: 1250,
    rewardXp: 25,
    fen: 'r3k2r/pppb1ppp/2n1pn2/3p4/2PP4/2N2N2/PP2PPPP/R2QKB1R w KQkq - 0 8',
    solution: [{ from: 'c3', to: 'b5' }],
    objective: 'Amenazar la casilla clave c7 con salto de caballo.',
    explanation: 'Cb5 amenaza Cc7+ con doblete letal a rey y torre.',
    alternative: 'La debilidad de c7 en las aperturas suele ser decisiva.',
  },
  {
    id: 'off-fork-04',
    title: 'Doble Ataque de Dama Central',
    category: 'basic-tactics',
    theme: 'fork',
    difficulty: 2,
    elo: 1300,
    rewardXp: 25,
    fen: 'r1b1k2r/pppp1ppp/8/4n3/1b2q3/2P5/PP2BPPP/RNBQK2R w KQkq - 0 9',
    solution: [{ from: 'd1', to: 'a4' }],
    objective: 'Dar jaque y atacar una pieza indefensa en la misma jugada.',
    explanation: 'Da4+ da jaque al rey y ataca al alfil desprotegido en b4.',
    alternative: 'Revisa siempre las piezas rivales sin protección.',
  },
  {
    id: 'off-fork-05',
    title: 'Tenedor de Alfil en Diagonal Larga',
    category: 'win-material',
    theme: 'fork',
    difficulty: 3,
    elo: 1400,
    rewardXp: 30,
    fen: 'r3k2r/8/8/8/8/8/1B6/4K3 w kq - 0 1',
    solution: [{ from: 'b2', to: 'h8' }],
    objective: 'Capturar la torre y mantener ataque.',
    explanation: 'Axh8 gana calidad limpia en la esquina.',
    alternative: 'Los alfiles en fianchetto barren ambas esquinas.',
  },
  {
    id: 'off-fork-06',
    title: 'Horquilla de Rey en Final de Peones',
    category: 'win-material',
    theme: 'fork',
    difficulty: 3,
    elo: 1450,
    rewardXp: 30,
    fen: '8/8/4k3/8/3n1n2/4K3/8/8 w - - 0 1',
    solution: [{ from: 'e3', to: 'e4' }],
    objective: 'Atacar dos caballos enemigos simultáneamente con el rey.',
    explanation: 'Re4 ataca ambos caballos negros que no pueden defenderse mutuamente.',
    alternative: 'Dos caballos no pueden protegerse el uno al otro.',
  },

  // --- CLAVADA / PIN (Intermedio ELO 1200 - 1650) ---
  {
    id: 'off-pin-01',
    title: 'Clavada Absoluta de Alfil',
    category: 'basic-tactics',
    theme: 'pin',
    difficulty: 2,
    elo: 1220,
    rewardXp: 25,
    fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/1bB1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 4',
    solution: [{ from: 'c1', to: 'g5' }],
    objective: 'Clavar el caballo enemigo contra su dama.',
    explanation: 'Ag5 clava al caballo de f6 que no puede moverse sin perder la dama.',
    alternative: 'Presiona las piezas clavadas añadiendo atacantes adicionales.',
  },
  {
    id: 'off-pin-02',
    title: 'Clavada en la Columna de Rey',
    category: 'win-material',
    theme: 'pin',
    difficulty: 3,
    elo: 1350,
    rewardXp: 30,
    fen: '4k3/4q3/8/8/8/8/4R3/4K3 w - - 0 1',
    solution: [{ from: 'e2', to: 'e7' }],
    objective: 'Aprovechar la inmovilidad de la dama enemiga.',
    explanation: 'Txe7+ captura la dama que estaba completamente paralizada por el rey.',
    alternative: 'Nunca coloques tu dama en la misma columna que tu rey desprotegido.',
  },
  {
    id: 'off-pin-03',
    title: 'Clavada Cruzada con Torre y Alfil',
    category: 'win-material',
    theme: 'pin',
    difficulty: 3,
    elo: 1480,
    rewardXp: 35,
    fen: 'r3k3/8/8/3b4/8/8/1B2R3/4K3 w - - 0 1',
    solution: [{ from: 'e2', to: 'd2' }],
    objective: 'Aumentar la presión sobre la pieza clavada.',
    explanation: 'Td2 añade un segundo atacante sobre el alfil clavado de d5.',
    alternative: 'La regla de oro de la clavada: ataca la pieza clavada tantas veces como sea posible.',
  },
  {
    id: 'off-pin-04',
    title: 'Clavada Relativa de Dama',
    category: 'win-material',
    theme: 'pin',
    difficulty: 3,
    elo: 1520,
    rewardXp: 35,
    fen: 'r3r1k1/ppp2ppp/2n5/8/8/2B5/PPP2PPP/R2Q2K1 w - - 0 1',
    solution: [{ from: 'd1', to: 'g4' }],
    objective: 'Alinear dama y alfil para amenazar mate en g7.',
    explanation: 'Dg4 amenaza Dxg7# explotando que las piezas negras están desconectadas.',
    alternative: 'Crea amenazas directas de mate cuando el rival no tiene defensores.',
  },
  {
    id: 'off-pin-05',
    title: 'Clavada con Ganancia de Dama',
    category: 'win-material',
    theme: 'pin',
    difficulty: 4,
    elo: 1600,
    rewardXp: 40,
    fen: '6k1/5pp1/8/8/8/8/B5q1/4K3 w - - 0 1',
    solution: [{ from: 'a2', to: 'd5' }],
    objective: 'Atacar la dama enemiga usando la clavada.',
    explanation: 'Ad5 ataca la dama; si se retira, queda expuesto el flanco.',
    alternative: 'Usa piezas menores para hostigar piezas mayores.',
  },

  // --- ATAQUE A LA DESCUBIERTA (Intermedio y Avanzado ELO 1350 - 1800) ---
  {
    id: 'off-disc-01',
    title: 'Jaque a la Descubierta con Alfil',
    category: 'basic-tactics',
    theme: 'discovered-attack',
    difficulty: 3,
    elo: 1380,
    rewardXp: 30,
    fen: 'r1bqk2r/pppp1ppp/2n5/4N3/1b2n3/2N5/PPPP1PPP/R1BQKB1R w KQkq - 0 5',
    solution: [{ from: 'e5', to: 'c6' }],
    objective: 'Mover el caballo para abrir la acción del alfil o la dama con jaque.',
    explanation: 'Cxc6+ descubre un ataque letal ganando la dama rival.',
    alternative: 'La pieza que se mueve puede capturar impunemente mientras la otra da jaque.',
  },
  {
    id: 'off-disc-02',
    title: 'Jaque Doble Imparable',
    category: 'basic-tactics',
    theme: 'discovered-attack',
    difficulty: 4,
    elo: 1580,
    rewardXp: 40,
    fen: 'r1b2rk1/pppp1ppp/8/8/1b1nN3/8/PPPP1PPP/R1B1KB1R w KQ - 0 1',
    solution: [{ from: 'e4', to: 'f6' }],
    objective: 'Dar jaque con caballo y descubrir jaque con alfil.',
    explanation: 'Cf6+ obliga al rey a moverse porque el jaque doble no permite bloquear ni capturar.',
    alternative: 'Ante un jaque doble, la única respuesta legal es mover el rey.',
  },
  {
    id: 'off-disc-03',
    title: 'Torre a la Descubierta en Columna Abierta',
    category: 'win-material',
    theme: 'discovered-attack',
    difficulty: 3,
    elo: 1450,
    rewardXp: 30,
    fen: 'r2q1rk1/ppp2ppp/2n1b3/3n4/3P4/2PB1N2/P4PPP/R1BQ1RK1 w - - 0 11',
    solution: [{ from: 'd3', to: 'h7' }],
    objective: 'Sacrificio temático clásico (Greek Gift) con jaque al rey.',
    explanation: 'Axh7+ abre el enroque negro y permite la entrada de Cg5+ y Dh5.',
    alternative: 'El sacrificio de alfil en h7 es uno de los ataques más famosos del ajedrez.',
  },
  {
    id: 'off-disc-04',
    title: 'Descubierta con Ganancia de Dama',
    category: 'win-material',
    theme: 'discovered-attack',
    difficulty: 4,
    elo: 1650,
    rewardXp: 40,
    fen: 'r1b1k2r/pppq1ppp/2n5/3NP3/1b6/5N2/PPPP1PPP/R1BQKB1R w KQkq - 1 7',
    solution: [{ from: 'd5', to: 'b4' }],
    objective: 'Retirar el caballo capturando y desenmascarando la dama.',
    explanation: 'Cxb4 gana pieza y abre la diagonal para presionar a la dama rival.',
    alternative: 'Combina capturas intermedias con ataques a la descubierta.',
  },
  {
    id: 'off-disc-05',
    title: 'Molino Táctico de Torre y Alfil',
    category: 'win-material',
    theme: 'discovered-attack',
    difficulty: 5,
    elo: 1850,
    rewardXp: 50,
    fen: '5rk1/5ppp/8/8/8/5B2/1R6/6K1 w - - 0 1',
    solution: [{ from: 'b2', to: 'g2' }],
    objective: 'Iniciar el mecanismo del molino jaqueando al rey.',
    explanation: 'Tg2+ obliga al rey a replegarse mientras el alfil controla la diagonal.',
    alternative: 'El molino permite capturar todas las piezas del rival mediante jaques alternados.',
  },

  // --- MATE EN 2 (Intermedio y Maestro ELO 1400 - 2100) ---
  {
    id: 'off-m2-01',
    title: 'Mate del Ahogado en Dos Tiempos',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 3,
    elo: 1450,
    rewardXp: 35,
    fen: 'r5rk/5p1p/5N2/8/8/8/5PPP/5RK1 w - - 0 1',
    solution: [{ from: 'f6', to: 'h7' }],
    objective: 'Dar jaque y forzar el mate inevitable en la siguiente jugada.',
    explanation: 'Ch7 remata con apoyo de la torre y amenazas al enroque.',
    alternative: 'Identifica la debilidad de las casillas f7 y h7.',
  },
  {
    id: 'off-m2-02',
    title: 'Desvío de Torre y Mate en Octava',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 3,
    elo: 1550,
    rewardXp: 35,
    fen: '3r2k1/5ppp/8/8/8/8/1Q3PPP/6K1 w - - 0 1',
    solution: [{ from: 'b2', to: 'b8' }],
    objective: 'Sacrificar la dama en la octava fila para desviar la torre rival.',
    explanation: 'Db8 clava la torre; tras Txb8 sigue Td8# con mate del pasillo.',
    alternative: 'La sobrecarga de piezas defensoras permite sacrificios de atracción.',
  },
  {
    id: 'off-m2-03',
    title: 'Sacrificio de Dama en h7',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 4,
    elo: 1720,
    rewardXp: 45,
    fen: 'r1b2rk1/ppp2ppp/8/3N4/2B5/8/PPP2PPP/R2Q1RK1 w - - 0 1',
    solution: [{ from: 'd5', to: 'e7' }],
    objective: 'Dar jaque con Ce7+ para forzar al rey a la esquina y rematar.',
    explanation: 'Ce7+ seguido de Dh5# remata la partida en dos tiempos.',
    alternative: 'Expulsa al rey rival hacia las casillas donde tu dama tiene acceso.',
  },
  {
    id: 'off-m2-04',
    title: 'Mate de Boden Cruzado',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 4,
    elo: 1800,
    rewardXp: 45,
    fen: '2kr3r/ppp2ppp/8/8/1B6/8/PPP2PPP/2KR1B1R w - - 0 1',
    solution: [{ from: 'd1', to: 'd8' }],
    objective: 'Desviar la defensa de la casilla de mate con alfiles.',
    explanation: 'Txd8+ despeja las diagonales para que los alfiles entreguen el mate de Boden.',
    alternative: 'Los alfiles en diagonales cruzadas forman una red de mate letal.',
  },
  {
    id: 'off-m2-05',
    title: 'Mate de la Ópera de Paul Morphy',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 4,
    elo: 1880,
    rewardXp: 50,
    fen: '4kb1r/p2n1ppp/4p3/8/3B4/8/PPP2PPP/R3K2R w KQk - 0 1',
    solution: [{ from: 'd4', to: 'a7' }],
    objective: 'Cerrar el escape del rey antes de la entrada de la torre.',
    explanation: 'Axa7 corta las casillas de escape preparando el mate en d8.',
    alternative: 'La combinación de Morphy ilustra el máximo valor del desarrollo rápido.',
  },
  {
    id: 'off-m2-06',
    title: 'Mate de Reti con Doble Alfil y Dama',
    category: 'mate-in-2',
    theme: 'mate-in-2',
    difficulty: 5,
    elo: 2050,
    rewardXp: 55,
    fen: 'rn2kbnr/pp3ppp/4p3/1B1p4/3q4/8/PPP2PPP/RNBQK2R w KQkq - 0 7',
    solution: [{ from: 'd1', to: 'd4' }],
    objective: 'Capturar la dama central y amenazar mate imparable.',
    explanation: 'Dxd4 gana la dama y mantiene el rey rival atrapado en el centro.',
    alternative: 'Castiga a quien saca la dama demasiado temprano en la apertura.',
  },

  // --- GANANCIA DE MATERIAL Y ESTRATEGIA (Intermedio y Avanzado ELO 1300 - 1900) ---
  {
    id: 'off-mat-01',
    title: 'Atracción a Casilla Fatal',
    category: 'win-material',
    theme: 'win-material',
    difficulty: 3,
    elo: 1420,
    rewardXp: 30,
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 4',
    solution: [{ from: 'd3', to: 'e4' }],
    objective: 'Eliminar la pieza central enemiga ganando ventaja de desarrollo.',
    explanation: 'dxe4 recupera material y abre la columna d para el ataque blanco.',
    alternative: 'No permitas que las piezas menores rivales se instalen en el centro.',
  },
  {
    id: 'off-mat-02',
    title: 'Sobrecarga de la Torre Defensora',
    category: 'win-material',
    theme: 'win-material',
    difficulty: 3,
    elo: 1540,
    rewardXp: 35,
    fen: '3r2k1/p4ppp/1p6/8/8/8/P4PPP/3R2K1 w - - 0 1',
    solution: [{ from: 'd1', to: 'd8' }],
    objective: 'Forzar la simplificación y ganar la octava fila.',
    explanation: 'Txd8+ elimina la única pieza activa del rival con jaque.',
    alternative: 'En finales con torre de ventaja, simplifica siempre que sea favorable.',
  },
  {
    id: 'off-mat-03',
    title: 'Desviación del Caballo Defensor',
    category: 'win-material',
    theme: 'win-material',
    difficulty: 4,
    elo: 1680,
    rewardXp: 40,
    fen: 'r1bqk2r/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 7',
    solution: [{ from: 'c4', to: 'd5' }],
    objective: 'Romper el centro y crear tensión táctica favorable.',
    explanation: 'cxd5 abre el centro y desorganiza la estructura de peones rival.',
    alternative: 'La ruptura de peones centrales genera diagonales y columnas abiertas.',
  },
  {
    id: 'off-mat-04',
    title: 'Intercepción de Línea de Defensa',
    category: 'win-material',
    theme: 'win-material',
    difficulty: 4,
    elo: 1750,
    rewardXp: 45,
    fen: 'r4rk1/ppp2ppp/8/3q4/3N4/8/PPP2PPP/R2Q1RK1 w - - 0 1',
    solution: [{ from: 'd4', to: 'f5' }],
    objective: 'Mejorar el caballo y atacar la dama rival.',
    explanation: 'Cf5 sitúa el caballo en una casilla agresiva amenazando Ce7+ y la dama.',
    alternative: 'Los puestos avanzados de caballo en f5 o d5 son devastadores.',
  },
  {
    id: 'off-mat-05',
    title: 'Rayos X a Través de la Torre',
    category: 'win-material',
    theme: 'win-material',
    difficulty: 5,
    elo: 1920,
    rewardXp: 50,
    fen: '3r2k1/5ppp/8/8/8/8/1R3PPP/1R4K1 w - - 0 1',
    solution: [{ from: 'b2', to: 'b8' }],
    objective: 'Aprovechar la duplicación de torres para romper la defensa.',
    explanation: 'Tb8 clava y gana la torre enemiga gracias al respaldo de la torre en b1.',
    alternative: 'Doblar torres en columnas abiertas ejerce máxima presión.',
  },

  // --- FINALES TÁCTICOS (Intermedio y Maestro ELO 1500 - 2300) ---
  {
    id: 'off-end-01',
    title: 'Oposición de Reyes en Final de Peones',
    category: 'best-move',
    theme: 'endgame',
    difficulty: 3,
    elo: 1520,
    rewardXp: 30,
    fen: '8/8/8/3k4/8/3K4/8/8 w - - 0 1',
    solution: [{ from: 'd3', to: 'e3' }],
    objective: 'Ganar la oposición directa para abrir camino a la coronación.',
    explanation: 'Re3 gana la oposición diagonal forzando al rey rival a ceder espacio.',
    alternative: 'Quien tiene la oposición directa controla las casillas clave.',
  },
  {
    id: 'off-end-02',
    title: 'Peón Pasado Alejado Decisivo',
    category: 'best-move',
    theme: 'endgame',
    difficulty: 3,
    elo: 1600,
    rewardXp: 35,
    fen: '8/p7/8/8/8/8/P7/k1K5 w - - 0 1',
    solution: [{ from: 'a2', to: 'a4' }],
    objective: 'Avanzar el peón alejado dos casillas para coronar primero.',
    explanation: 'a4 acelera la coronación mientras el rey rival queda fuera del cuadrado.',
    alternative: 'Usa la regla del cuadrado para calcular si el rey enemigo alcanza a tu peón.',
  },
  {
    id: 'off-end-03',
    title: 'Triangulación de Rey en Final',
    category: 'best-move',
    theme: 'endgame',
    difficulty: 4,
    elo: 1820,
    rewardXp: 45,
    fen: '8/8/8/4k3/8/4K3/8/8 w - - 0 1',
    solution: [{ from: 'e3', to: 'd3' }],
    objective: 'Ceder un tiempo mediante triangulación para forzar zugzwang.',
    explanation: 'Rd3 maniobra para colocar al rival en turno desfavorable.',
    alternative: 'Zugzwang: la obligación de mover empeora la posición del rival.',
  },
  {
    id: 'off-end-04',
    title: 'Final de Lucena: Puente de Torre',
    category: 'best-move',
    theme: 'endgame',
    difficulty: 5,
    elo: 2100,
    rewardXp: 55,
    fen: '1K1k4/1P6/8/8/8/8/7r/2R5 w - - 0 1',
    solution: [{ from: 'c1', to: 'c4' }],
    objective: 'Construir el puente de Lucena en la cuarta fila para coronar el peón.',
    explanation: 'Tc4 prepara el escudo contra los jaques verticales de la torre rival.',
    alternative: 'La posición de Lucena es la técnica fundamental para ganar finales de torre y peón.',
  },
  {
    id: 'off-end-05',
    title: 'Defensa de Philidor: Jaques por Detrás',
    category: 'defend-position',
    theme: 'endgame',
    difficulty: 5,
    elo: 2200,
    rewardXp: 60,
    fen: '3k4/8/3K4/3P4/8/8/7r/5R2 w - - 0 1',
    solution: [{ from: 'f1', to: 'f8' }],
    objective: 'Buscar el mate en octava o cortar al rey enemigo.',
    explanation: 'Tf8# remata la posición aprovechando el control del rey en d6.',
    alternative: 'En la defensa de Philidor, mantén la torre en sexta fila hasta que el peón avance.',
  },
  {
    id: 'off-end-06',
    title: 'Ruptura de Peones en Final Artístico',
    category: 'win-material',
    theme: 'endgame',
    difficulty: 5,
    elo: 2350,
    rewardXp: 65,
    fen: '8/ppp5/8/PPP5/8/8/8/4K2k w - - 0 1',
    solution: [{ from: 'b5', to: 'b6' }],
    objective: 'Sacrificar un peón para abrir paso imparable al peón de flanco.',
    explanation: 'b6! rompe la estructura enemiga garantizando la coronación de un peón en 3 jugadas.',
    alternative: 'La ruptura b6 en estructuras de 3 contra 3 es un tema clásico de finales.',
  },
];
