import type { CosmeticItem, PlayerCustomization } from './cosmetics-types';

export const DEFAULT_PLAYER_CUSTOMIZATION: PlayerCustomization = {
  name: 'Kepa',
  avatarId: 'avatar_leo',
  frameId: 'frame_default',
  countryCode: 'ES',
  favoriteColor: '#00E5FF',
  motto: 'El cálculo puro vence al azar.',
};

export const COSMETIC_ITEMS: readonly CosmeticItem[] = [
  // ==================== AVATARES / PERSONAJES ====================
  {
    id: 'avatar_leo',
    name: 'Leo',
    category: 'avatars',
    rarity: 'comun',
    description: 'Aspirante creativo con gran intuición para los ataques rápidos.',
    icon: '👦',
    previewAsset: '👦',
    priceCoins: 0,
  },
  {
    id: 'avatar_maya',
    name: 'Maya',
    category: 'avatars',
    rarity: 'especial',
    description: 'Táctica audaz especialista en combinaciones fulminantes.',
    icon: '👩‍🎤',
    previewAsset: '👩‍🎤',
    priceCoins: 350,
    unlockLevel: 3,
  },
  {
    id: 'avatar_akira',
    name: 'Akira',
    category: 'avatars',
    rarity: 'especial',
    description: 'Calculador disciplinado con precisión milimétrica.',
    icon: '🥋',
    previewAsset: '🥋',
    priceCoins: 500,
    unlockLevel: 5,
  },
  {
    id: 'avatar_luna',
    name: 'Luna',
    category: 'avatars',
    rarity: 'epico',
    description: 'Estratega posicional que asfixia el espacio de sus rivales.',
    icon: '🌙',
    previewAsset: '🌙',
    priceCoins: 750,
    unlockLevel: 8,
  },
  {
    id: 'avatar_viktor',
    name: 'Viktor',
    category: 'avatars',
    rarity: 'epico',
    description: 'Maestro del contrajuego agudo y sacrificios de calidad.',
    icon: '🕵️‍♂️',
    previewAsset: '🕵️‍♂️',
    priceCoins: 900,
    unlockLevel: 12,
  },
  {
    id: 'avatar_sofia',
    name: 'Sofía',
    category: 'avatars',
    rarity: 'legendario',
    description: 'Gran Maestra zen de los finales de torres y alfiles.',
    icon: '🧘‍♀️',
    previewAsset: '🧘‍♀️',
    priceCoins: 1500,
    unlockLevel: 18,
  },
  {
    id: 'avatar_mateo',
    name: 'Mateo',
    category: 'avatars',
    rarity: 'legendario',
    description: 'Guerrero implacable del tablero, siempre en busca del rey rival.',
    icon: '⚔️',
    previewAsset: '⚔️',
    priceCoins: 1800,
    unlockLevel: 25,
  },
  {
    id: 'avatar_nora',
    name: 'Nora Suprema',
    category: 'avatars',
    rarity: 'campeon',
    description: 'Corona legendaria de la Campeona del Mundo AjedrezPro.',
    icon: '👑',
    previewAsset: '👑',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el Campeonato del Mundo AjedrezPro en Modo Carrera',
  },

  // ==================== MARCOS DE PERFIL ====================
  {
    id: 'frame_default',
    name: 'Marco Estándar',
    category: 'frames',
    rarity: 'comun',
    description: 'Borde limpio de titanio para tu perfil.',
    icon: '⬜',
    previewAsset: '#1E293B',
    priceCoins: 0,
  },
  {
    id: 'frame_bronze',
    name: 'Marco Bronce de Club',
    category: 'frames',
    rarity: 'especial',
    description: 'Galardón de bronce forjado para jugadores de club.',
    icon: '🥉',
    previewAsset: '#CD7F32',
    priceCoins: 250,
    unlockLevel: 3,
  },
  {
    id: 'frame_silver',
    name: 'Marco Plata Regional',
    category: 'frames',
    rarity: 'epico',
    description: 'Plata pulida otorgada a los mejores de la región.',
    icon: '🥈',
    previewAsset: '#E2E8F0',
    priceCoins: 600,
    unlockLevel: 10,
  },
  {
    id: 'frame_gold',
    name: 'Marco Oro Nacional',
    category: 'frames',
    rarity: 'legendario',
    description: 'Oro real resplandeciente reservado a maestros nacionales.',
    icon: '🥇',
    previewAsset: '#F5C518',
    priceCoins: 1200,
    unlockLevel: 20,
  },
  {
    id: 'frame_neon_cyan',
    name: 'Marco Neón Ciberespacio',
    category: 'frames',
    rarity: 'legendario',
    description: 'Aura futurista de luz azul eléctrico de alta tecnología.',
    icon: '💠',
    previewAsset: '#00E5FF',
    priceCoins: 1400,
  },
  {
    id: 'frame_champion_crown',
    name: 'Marco Corona Mundial',
    category: 'frames',
    rarity: 'campeon',
    description: 'El marco definitivo de diamantes y oro del monarca mundial.',
    icon: '👑',
    previewAsset: '#FFD700',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el Campeonato del Mundo AjedrezPro',
  },

  // ==================== TABLEROS ====================
  {
    id: 'board_classic',
    name: 'Royale Azul & Oro (Flagship)',
    category: 'boards',
    rarity: 'comun',
    description: 'El tablero insignia de AjedrezPro. Máxima legibilidad y elegancia.',
    icon: '🔷',
    previewAsset: 'classic',
    priceCoins: 0,
  },
  {
    id: 'board_walnut',
    name: 'Nogal Clásico de Torneo',
    category: 'boards',
    rarity: 'especial',
    description: 'Madera noble tradicional con acabado de club profesional.',
    icon: '🪵',
    previewAsset: 'walnut',
    priceCoins: 350,
    unlockLevel: 2,
  },
  {
    id: 'board_marble',
    name: 'Mármol Blanco Imperial',
    category: 'boards',
    rarity: 'epico',
    description: 'Piedra pulida de alto contraste para maestros exigentes.',
    icon: '🏛️',
    previewAsset: 'marble',
    priceCoins: 650,
    unlockLevel: 5,
  },
  {
    id: 'board_fide_blue',
    name: 'Azul Oficial de Competición',
    category: 'boards',
    rarity: 'epico',
    description: 'Estilo oficial de retransmisiones internacionales.',
    icon: '🟦',
    previewAsset: 'fide-blue',
    priceCoins: 800,
  },
  {
    id: 'board_dark_neon',
    name: 'Neón Ciberpunk Oscuro',
    category: 'boards',
    rarity: 'legendario',
    description: 'Obsidiana profunda con bordes electrizantes de alto impacto.',
    icon: '🔮',
    previewAsset: 'dark-neon',
    priceCoins: 1100,
  },
  {
    id: 'board_royal_gold',
    name: 'Oro Real & Obsidiana',
    category: 'boards',
    rarity: 'legendario',
    description: 'Lujo absoluto en pan de oro y piedras preciosas.',
    icon: '🏆',
    previewAsset: 'royal-gold',
    priceCoins: 1600,
    unlockLevel: 20,
  },
  {
    id: 'board_champion',
    name: 'Tablero Campeonato del Mundo',
    category: 'boards',
    rarity: 'campeon',
    description: 'El tablero histórico sobre el que se corona el Rey del Ajedrez.',
    icon: '👑',
    previewAsset: 'neon-cyber',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el Campeonato del Mundo en Modo Carrera',
  },
  {
    id: 'board_bilbao',
    name: 'Tablero Bilbao Open',
    category: 'boards',
    rarity: 'especial',
    description: 'Acero cepillado y titanio obtenido al coronarse en el Bilbao Open.',
    icon: '🏛️',
    previewAsset: 'bilbao',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el Bilbao Open en Modo Carrera',
  },
  {
    id: 'board_madrid',
    name: 'Tablero Madrid Masters',
    category: 'boards',
    rarity: 'epico',
    description: 'Granito noble y oro forjado en la capital española.',
    icon: '🏰',
    previewAsset: 'madrid',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el Madrid Masters en Modo Carrera',
  },
  {
    id: 'board_paris',
    name: 'Tablero París Grand Prix',
    category: 'boards',
    rarity: 'legendario',
    description: 'Mármol fino y azul zafiro imperial de la Ciudad de la Luz.',
    icon: '🗼',
    previewAsset: 'paris',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el París Grand Prix en Modo Carrera',
  },
  {
    id: 'board_london',
    name: 'Tablero Londres Clásico',
    category: 'boards',
    rarity: 'legendario',
    description: 'Madera de caoba victoriana tradicional de la cuna del ajedrez moderno.',
    icon: '💂',
    previewAsset: 'london',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana el London Chess Classic en Modo Carrera',
  },
  {
    id: 'board_kids_castle',
    name: 'Tablero Castillo Mágico Kids',
    category: 'boards',
    rarity: 'comun',
    description: 'Colores vibrantes y amigables diseñados para jóvenes campeones.',
    icon: '🏰',
    previewAsset: 'kids-castle',
    priceCoins: 0,
  },

  // ==================== SETS DE PIEZAS ====================
  {
    id: 'piece_staunton',
    name: 'Staunton Clásico Pro (Default)',
    category: 'pieces',
    rarity: 'comun',
    description: 'Siluetas perfeccionadas FIDE de máxima claridad y contraste.',
    icon: '♞',
    previewAsset: 'staunton',
    priceCoins: 0,
  },
  {
    id: 'piece_kids_classic',
    name: 'Kids Clásico Amigable',
    category: 'pieces',
    rarity: 'comun',
    description: 'Siluetas Staunton redondeadas y amigables para niños y principiantes.',
    icon: '🧸',
    previewAsset: 'kids-classic',
    priceCoins: 0,
  },
  {
    id: 'piece_modern',
    name: 'Moderna Neón Minimalista',
    category: 'pieces',
    rarity: 'especial',
    description: 'Líneas limpias y geométricas de diseño contemporáneo.',
    icon: '♟️',
    previewAsset: 'modern',
    priceCoins: 450,
    unlockLevel: 4,
  },
  {
    id: 'piece_realistic_3d',
    name: '3D Esculpida Élite',
    category: 'pieces',
    rarity: 'legendario',
    description: 'Volumen y relieve artesanal con acabado pulido.',
    icon: '🗿',
    previewAsset: '3d-realistic',
    priceCoins: 950,
    unlockLevel: 10,
  },
  {
    id: 'piece_champion_gold',
    name: 'Piezas Oro Supremo',
    category: 'pieces',
    rarity: 'campeon',
    description: 'Acabado dorado metálico exclusivo para campeones consagrados.',
    icon: '👑',
    previewAsset: 'realistic-3d',
    priceCoins: 0,
    isAchievementExclusive: true,
    achievementRequirement: 'Gana la Copa Mundial o el Campeonato del Mundo',
  },
] as const;

export function getCosmeticById(id: string): CosmeticItem | undefined {
  return COSMETIC_ITEMS.find((item) => item.id === id);
}

export function getCosmeticsByCategory(category: CosmeticItem['category']): CosmeticItem[] {
  return COSMETIC_ITEMS.filter((item) => item.category === category);
}
