import type { SchoolLesson } from './school-types';

export const SCHOOL_LESSONS: readonly SchoolLesson[] = [
  // ==================== 1. EL PEÓN (SOLDADO) ====================
  {
    id: 'pawn',
    order: 1,
    pieceName: 'El Peón',
    pieceSymbol: '♙',
    kidsName: 'El Pequeño Soldado',
    kidsIcon: '🛡️',
    themeColor: '#10B981',
    introTitle: '¡Conoce al Soldado del Reino!',
    introStory:
      'Los peones son los valientes soldados que marchan siempre hacia adelante. Nunca retroceden.',
    movementRules:
      'El peón avanza 1 casilla hacia adelante. En su primer movimiento puede avanzar 1 o 2 casillas. ¡Y captura en diagonal!',
    demonstrationFen: '8/8/8/8/8/8/4P3/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Soldado Explorador 🛡️',
      kidsEmoji: '🛡️',
      classicName: 'Peón Clásico ♙',
      classicSymbol: '♙',
      explanation:
        'En los tableros tradicionales se representa como una esfera sobre un cuerpo cilíndrico.',
    },
    exercises: [
      {
        id: 'pawn_ex1',
        title: 'La Gran Marcha del Peón',
        instructions: 'Mueve el peón 2 casillas en su primer paso para llegar a e4.',
        coachTip: 'En la casilla inicial e2, el peón puede dar un salto doble hasta e4.',
        initialFen: '8/8/8/8/8/8/4P3/4K2k w - - 0 1',
        targetPieceSquare: 'e2',
        goalSquares: ['e4'],
        optimalMoves: 1,
        maxAllowedMoves: 2,
        profeProPraise: '¡Excelente salto doble! Has aprendido el primer paso del peón.',
        profeProCorrection: 'Recuerda que desde la casilla inicial puedes avanzar 2 casillas.',
      },
      {
        id: 'pawn_ex2',
        title: 'La Captura Diagonal',
        instructions: '¡Captura el peón negro en diagonal hacia d5!',
        coachTip: 'Los peones se mueven hacia adelante pero capturan en diagonal.',
        initialFen: '8/8/8/3p4/4P3/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'e4',
        goalSquares: ['d5'],
        targetCaptureSquares: ['d5'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Diana! Capturaste el peón en diagonal con precisión.',
        profeProCorrection: 'Captura el peón en d5 en diagonal hacia adelante.',
      },
    ],
    rewardXp: 50,
    rewardCoins: 50,
  },

  // ==================== 2. LA TORRE (CASTILLO) ====================
  {
    id: 'rook',
    order: 2,
    pieceName: 'La Torre',
    pieceSymbol: '♖',
    kidsName: 'El Gran Castillo',
    kidsIcon: '🏰',
    themeColor: '#3B82F6',
    introTitle: '¡El Poder de la Torre Fortaleza!',
    introStory:
      'La torre es una fortaleza veloz. Puede cruzar el tablero entero en línea recta como un rayo.',
    movementRules:
      'La torre se mueve en línea recta horizontal (filas) y vertical (columnas) todas las casillas que quiera.',
    demonstrationFen: '8/8/8/8/3R4/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Castillo Fortaleza 🏰',
      kidsEmoji: '🏰',
      classicName: 'Torre de Torneo ♖',
      classicSymbol: '♖',
      explanation:
        'En los sets oficiales Staunton tiene forma de almena de castillo con 4 ranuras.',
    },
    exercises: [
      {
        id: 'rook_ex1',
        title: 'El Rayo Vertical',
        instructions: 'Desplaza la torre hacia arriba en línea recta hasta e8.',
        coachTip: 'La torre puede recorrer toda la columna de un solo movimiento.',
        initialFen: '8/8/8/8/8/8/8/4R1Kk w - - 0 1',
        targetPieceSquare: 'e1',
        goalSquares: ['e8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Impresionante velocidad! La torre limpió toda la columna.',
        profeProCorrection: 'Mueve la torre hacia arriba en línea recta por la columna e.',
      },
      {
        id: 'rook_ex2',
        title: 'Ruta en Dos Tramos',
        instructions: 'Lleva la torre a b5 usando líneas rectas.',
        coachTip: 'Desplaza la torre en línea recta por la columna b.',
        initialFen: '8/8/8/8/8/8/8/1R4Kk w - - 0 1',
        targetPieceSquare: 'b1',
        goalSquares: ['b5'],
        optimalMoves: 1,
        maxAllowedMoves: 2,
        profeProPraise: '¡Perfecto! Dominas el movimiento horizontal y vertical de la torre.',
        profeProCorrection: 'Recuerda que la torre viaja en línea recta (+).',
      },
    ],
    rewardXp: 60,
    rewardCoins: 60,
  },

  // ==================== 3. EL ALFIL (MAGO) ====================
  {
    id: 'bishop',
    order: 3,
    pieceName: 'El Alfil',
    pieceSymbol: '♗',
    kidsName: 'El Mago de las Diagonales',
    kidsIcon: '🧙‍♂️',
    themeColor: '#8B5CF6',
    introTitle: '¡La Magia de las Diagonales!',
    introStory:
      'El alfil es el consejero veloz del rey. Se desliza como un rayo mágico por las diagonales.',
    movementRules:
      'El alfil se mueve siempre en diagonal todas las casillas que desee, manteniéndose siempre en casillas de su mismo color.',
    demonstrationFen: '8/8/8/8/3B4/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Mago Sabio 🧙‍♂️',
      kidsEmoji: '🧙‍♂️',
      classicName: 'Alfil Clásico ♗',
      classicSymbol: '♗',
      explanation:
        'En los sets tradicionales se reconoce por la mitra redondeada con un corte diagonal.',
    },
    exercises: [
      {
        id: 'bishop_ex1',
        title: 'El Vuelo Diagonal',
        instructions: 'Desplaza el alfil por la gran diagonal hasta h8.',
        coachTip: 'Sigue la línea diagonal de casillas oscuras hasta llegar a h8.',
        initialFen: '8/8/8/8/8/8/8/B5Kk w - - 0 1',
        targetPieceSquare: 'a1',
        goalSquares: ['h8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Mágico! Tu alfil cruzó el tablero entero por su diagonal.',
        profeProCorrection: 'El alfil solo viaja en diagonal (X), sin cambiar de color de casilla.',
      },
      {
        id: 'bishop_ex2',
        title: 'Zig-Zag Diagonal',
        instructions: 'Mueve el alfil en diagonal hasta e4.',
        coachTip: 'Viaja en diagonal de b1 a e4.',
        initialFen: '8/8/8/8/8/8/8/1B4Kk w - - 0 1',
        targetPieceSquare: 'b1',
        goalSquares: ['e4'],
        optimalMoves: 1,
        maxAllowedMoves: 2,
        profeProPraise: '¡Fantástico tiro diagonal! Ya dominas la visión diagonal.',
        profeProCorrection: 'Revisa las diagonales que conectan con la casilla e4.',
      },
    ],
    rewardXp: 70,
    rewardCoins: 70,
  },

  // ==================== 4. LA DAMA (REINA) ====================
  {
    id: 'queen',
    order: 4,
    pieceName: 'La Dama',
    pieceSymbol: '♕',
    kidsName: 'La Reina Suprema',
    kidsIcon: '👸',
    themeColor: '#EC4899',
    introTitle: '¡La Pieza Más Poderosa del Tablero!',
    introStory:
      'La Dama es la líder del ejército. Combina la fuerza de la Torre y del Alfil en una sola pieza.',
    movementRules:
      'La Dama puede moverse todas las casillas que quiera en cualquier dirección: horizontal, vertical o diagonal.',
    demonstrationFen: '8/8/8/8/3Q4/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Reina Majestuosa 👸',
      kidsEmoji: '👸',
      classicName: 'Dama Staunton ♕',
      classicSymbol: '♕',
      explanation:
        'En los sets clásicos se distingue por una corona circular con múltiples puntas y perlas.',
    },
    exercises: [
      {
        id: 'queen_ex1',
        title: 'El Poder Total de la Dama',
        instructions: 'Alcanza la casilla h8 en una sola jugada usando su alcance máximo.',
        coachTip: 'La Dama puede viajar en línea recta o diagonal indistintamente.',
        initialFen: '8/8/8/8/3Q4/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'd4',
        goalSquares: ['h8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Extraordinario! La Dama demostró su inmenso poder.',
        profeProCorrection: 'Recuerda que la Dama combina el movimiento de la Torre y del Alfil.',
      },
      {
        id: 'queen_ex2',
        title: 'La Dama Central',
        instructions: 'Desplaza la Dama a d8 dominando la columna.',
        coachTip: 'Avanza verticalmente por la columna d.',
        initialFen: '8/8/8/8/3Q4/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'd4',
        goalSquares: ['d8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Eres un maestro con la Dama! Controlas todas las direcciones.',
        profeProCorrection: 'Mueve la Dama en línea recta a d8.',
      },
    ],
    rewardXp: 80,
    rewardCoins: 80,
  },

  // ==================== 5. EL REY (MONARCA) ====================
  {
    id: 'king',
    order: 5,
    pieceName: 'El Rey',
    pieceSymbol: '♔',
    kidsName: 'El Rey Soberano',
    kidsIcon: '👑',
    themeColor: '#F59E0B',
    introTitle: '¡El Corazón del Reino!',
    introStory:
      'El Rey es la pieza más importante del juego. Si el Rey cae en jaque mate, la partida termina.',
    movementRules:
      'El Rey se mueve solo 1 casilla en cualquier dirección (horizontal, vertical o diagonal). No puede pisar casillas atacadas.',
    demonstrationFen: '8/8/8/8/3K4/4P3/8/4k3 w - - 0 1',
    realPieceComparison: {
      kidsName: 'Rey Soberano 👑',
      kidsEmoji: '👑',
      classicName: 'Rey Staunton ♔',
      classicSymbol: '♔',
      explanation:
        'En los sets tradicionales es la pieza más alta de todas y lleva una cruz en la cúspide.',
    },
    exercises: [
      {
        id: 'king_ex1',
        title: 'Paso a Paso del Monarca',
        instructions: 'Mueve el rey 1 casilla en diagonal a e5.',
        coachTip: 'El rey camina despacio: solo 1 casilla por turno.',
        initialFen: '8/8/8/8/3K4/4P3/8/4k3 w - - 0 1',
        targetPieceSquare: 'd4',
        goalSquares: ['e5'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Digno paso real! El rey avanza seguro.',
        profeProCorrection: 'El rey solo puede desplazarse a casillas vecinas a 1 casilla de distancia.',
      },
      {
        id: 'king_ex2',
        title: 'El Paseo del Rey',
        instructions: 'Lleva al rey a g2 paso a paso.',
        coachTip: 'Muévete 1 casilla hacia la meta.',
        initialFen: '8/8/8/8/8/8/4P3/4k2K w - - 0 1',
        targetPieceSquare: 'h1',
        goalSquares: ['g2'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Bien protegido! Tu rey está sano y salvo.',
        profeProCorrection: 'El rey se mueve 1 paso hacia la casilla contigua.',
      },
    ],
    rewardXp: 90,
    rewardCoins: 90,
  },

  // ==================== 6. EL CABALLO (CORCEL) ====================
  {
    id: 'knight',
    order: 6,
    pieceName: 'El Caballo',
    pieceSymbol: '♘',
    kidsName: 'El Corcel Saltarín',
    kidsIcon: '🐴',
    themeColor: '#00E5FF',
    introTitle: '¡El Único que Salta por los Aires!',
    introStory:
      'El caballo es la pieza más divertida y sorprendente. ¡Es la única pieza que puede saltar por encima de las demás!',
    movementRules:
      'El caballo se mueve en forma de L: 2 casillas en línea recta y luego 1 casilla a un lado. Siempre cambia de color de casilla.',
    demonstrationFen: '8/8/8/8/3N4/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Corcel Aventurero 🐴',
      kidsEmoji: '🐴',
      classicName: 'Caballo Staunton ♘',
      classicSymbol: '♘',
      explanation:
        'En los sets clásicos está esculpido como la cabeza y cuello de un caballo de combate.',
    },
    exercises: [
      {
        id: 'knight_ex1',
        title: 'El Gran Salto en L',
        instructions: 'Salta con el caballo formando una L (2 casillas arriba y 1 a la derecha) hasta f3.',
        coachTip: 'Cuenta: 1, 2 hacia adelante... ¡y 1 al lado!',
        initialFen: '8/8/8/8/8/8/8/4N1Kk w - - 0 1',
        targetPieceSquare: 'e1',
        goalSquares: ['f3'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Salto perfecto! Has dominado el secreto del caballo.',
        profeProCorrection: 'Recuerda el patrón en L: 2 pasos rectos y 1 perpendicular.',
      },
      {
        id: 'knight_ex2',
        title: 'Saltando Obstáculos',
        instructions: 'Salta por encima de los peones hasta d3.',
        coachTip: 'El caballo no se choca con las piezas intermedias: ¡salta por el aire!',
        initialFen: '8/8/8/8/8/8/4pp2/4N1Kk w - - 0 1',
        targetPieceSquare: 'e1',
        goalSquares: ['d3'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Increíble salto acrobático! Ningún obstáculo detiene a tu caballo.',
        profeProCorrection: 'El caballo vuela sobre peones. Busca la casilla en L.',
      },
    ],
    rewardXp: 100,
    rewardCoins: 100,
    rewardItemId: 'piece_kids_classic',
  },

  // ==================== 7. EL JAQUE ====================
  {
    id: 'check',
    order: 7,
    pieceName: 'El Jaque',
    pieceSymbol: '⚡',
    kidsName: '¡Alerta Real! El Jaque',
    kidsIcon: '⚡',
    themeColor: '#EF4444',
    introTitle: '¡El Rey está Bajo Ataque!',
    introStory:
      'Cuando una pieza ataca directamente al Rey rival, se llama ¡JAQUE! El Rey rival debe defenderse inmediatamente.',
    movementRules:
      'Da un jaque moviendo una pieza a una casilla donde amenace directamente al Rey enemigo.',
    demonstrationFen: '4k3/8/8/8/8/8/8/4R1K1 w - - 0 1',
    realPieceComparison: {
      kidsName: 'Alerta de Escudo ⚡',
      kidsEmoji: '⚡',
      classicName: 'Jaque al Rey (+)',
      classicSymbol: '+',
      explanation:
        'En la notación oficial se anota con el signo "+" al final de la jugada.',
    },
    exercises: [
      {
        id: 'check_ex1',
        title: '¡Jaque con la Torre!',
        instructions: 'Mueve la torre para dar jaque directo al rey enemigo en e8.',
        coachTip: 'Coloca la torre en la misma columna e para poner al rey en jaque.',
        initialFen: '4k3/8/8/8/8/8/8/1R4K1 w - - 0 1',
        targetPieceSquare: 'b1',
        goalSquares: ['e1'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Jaque perfecto! El rey enemigo tiembla ante tu torre.',
        profeProCorrection: 'Lleva la torre a la columna del rey rival para atacarlo.',
      },
      {
        id: 'check_ex2',
        title: '¡Jaque Diagonal con el Alfil!',
        instructions: 'Mueve el alfil a c4 para dar un jaque certero al rey en f7.',
        coachTip: 'Coloca el alfil en la diagonal a2-g8 que apunta directamente al rey.',
        initialFen: '8/5k2/8/8/8/8/8/2B1K3 w - - 0 1',
        targetPieceSquare: 'c1',
        goalSquares: ['c4'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Jaque diagonal magistral! El alfil apunta al corazón rival.',
        profeProCorrection: 'Lleva el alfil a la casilla c4 apuntando en diagonal.',
      },
    ],
    rewardXp: 110,
    rewardCoins: 110,
  },

  // ==================== 8. SALIR DEL JAQUE ====================
  {
    id: 'escape_check',
    order: 8,
    pieceName: 'Salir del Jaque',
    pieceSymbol: '🛡️',
    kidsName: 'Escape y Rescate Real',
    kidsIcon: '🛡️',
    themeColor: '#F97316',
    introTitle: '¡Salva a tu Rey del Peligro!',
    introStory:
      '¡Tu Rey está en jaque! Hay tres formas de salvarse: Mover el rey (huir), Bloquear con otra pieza o Capturar la pieza atacante.',
    movementRules:
      'Cuando estés en jaque, es obligatorio salvar al Rey en la siguiente jugada.',
    demonstrationFen: '4r3/8/8/8/8/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Plan de Escape 🛡️',
      kidsEmoji: '🛡️',
      classicName: 'Defensa del Jaque',
      classicSymbol: '🛡️',
      explanation:
        'Las 3 reglas de oro: Huir (Mover Rey), Interponer (Bloquear) o Capturar.',
    },
    exercises: [
      {
        id: 'escape_check_ex1',
        title: 'Huir a una Casilla Segura',
        instructions: 'El rey blanco está en jaque por la torre en e8. Muévelo a f1 para estar a salvo.',
        coachTip: 'Sal de la columna e hacia una casilla que no esté amenazada.',
        initialFen: '4r3/8/8/8/8/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'e1',
        goalSquares: ['f1'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Rey a salvo! Escapaste del peligro con gran maestría.',
        profeProCorrection: 'Mueve el rey fuera de la línea de ataque de la torre.',
      },
      {
        id: 'escape_check_ex2',
        title: 'Bloquear con el Alfil',
        instructions: 'Bloquea el jaque de la torre interponiendo el alfil en e2.',
        coachTip: 'Coloca el alfil como escudo protector entre el rey y la torre.',
        initialFen: '4r3/8/8/8/8/8/8/2B1K2k w - - 0 1',
        targetPieceSquare: 'c1',
        goalSquares: ['e2'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Escudo impenetrable! El alfil neutralizó el ataque.',
        profeProCorrection: 'Interpón el alfil en la casilla e2 para bloquear la columna.',
      },
    ],
    rewardXp: 120,
    rewardCoins: 120,
  },

  // ==================== 9. JAQUE MATE ====================
  {
    id: 'checkmate',
    order: 9,
    pieceName: 'Jaque Mate',
    pieceSymbol: '🏆',
    kidsName: '¡Jaque Mate! Victoria Final',
    kidsIcon: '🏆',
    themeColor: '#DC2626',
    introTitle: '¡El Gran Triunfo del Ajedrez!',
    introStory:
      '¡Jaque Mate significa que el Rey rival está atacado y NO tiene escapatoria! ¡La partida termina con tu victoria!',
    movementRules:
      'Da jaque mate acorralando al Rey enemigo para que no pueda huir, bloquear ni capturar.',
    demonstrationFen: '6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
    realPieceComparison: {
      kidsName: 'Corona de Victoria 🏆',
      kidsEmoji: '🏆',
      classicName: 'Jaque Mate (#)',
      classicSymbol: '#',
      explanation:
        'En notación oficial se escribe "#". Marca el fin inmediato de la partida.',
    },
    exercises: [
      {
        id: 'checkmate_ex1',
        title: 'El Mate del Pasillo',
        instructions: 'Lleva la torre hasta b8 para dar jaque mate en la última fila.',
        coachTip: 'El rey rival está encerrado tras sus propios peones. ¡Aprovecha la última fila!',
        initialFen: '6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
        targetPieceSquare: 'b1',
        goalSquares: ['b8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡JAQUE MATE! ¡Has ganado la partida como un auténtico campeón!',
        profeProCorrection: 'Coloca la torre en la 8ª fila para encerrar al rey enemigo.',
      },
      {
        id: 'checkmate_ex2',
        title: 'Mate en la Última Fila',
        instructions: 'Mueve la Dama a e8 para dar jaque mate.',
        coachTip: 'La Dama penetra en la 8ª fila para asestar el mate definitivo.',
        initialFen: '6k1/5p1p/8/8/8/8/8/4Q1K1 w - - 0 1',
        targetPieceSquare: 'e1',
        goalSquares: ['e8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Jaque mate fulminante! ¡Victoria total!',
        profeProCorrection: 'Lleva la Dama a e8 frente a los peones rivales.',
      },
    ],
    rewardXp: 130,
    rewardCoins: 130,
  },

  // ==================== 10. EL ENROQUE ====================
  {
    id: 'castling',
    order: 10,
    pieceName: 'El Enroque',
    pieceSymbol: '🏰',
    kidsName: 'El Castillo Protector (Enroque)',
    kidsIcon: '🏰',
    themeColor: '#059669',
    introTitle: '¡El Movimiento Especial de Dos Piezas!',
    introStory:
      'El enroque es un movimiento mágico donde el Rey y la Torre se mueven a la vez para proteger al Rey en su castillo.',
    movementRules:
      'El Rey se desplaza dos casillas hacia la torre, y la torre salta al lado del rey. ¡Solo es válido si ninguna se ha movido antes!',
    demonstrationFen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
    realPieceComparison: {
      kidsName: 'Escudo del Castillo 🏰',
      kidsEmoji: '🏰',
      classicName: 'Enroque (0-0 / 0-0-0)',
      classicSymbol: 'O-O',
      explanation:
        '0-0 es el enroque corto (lado rey) y 0-0-0 es el enroque largo (lado dama).',
    },
    exercises: [
      {
        id: 'castling_ex1',
        title: 'El Enroque Corto',
        instructions: 'Mueve el rey blanco dos casillas a g1 para completar el enroque corto.',
        coachTip: 'Haz clic en el rey e1 y muévelo a g1. ¡La torre en h1 saltará automáticamente a f1!',
        initialFen: 'rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
        targetPieceSquare: 'e1',
        goalSquares: ['g1'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Enroque perfecto! Tu rey descansa seguro en su castillo de peones.',
        profeProCorrection: 'Mueve el rey dos casillas a la derecha hacia g1.',
      },
      {
        id: 'castling_ex2',
        title: 'El Enroque Largo',
        instructions: 'Mueve el rey blanco dos casillas a c1 para realizar el enroque largo.',
        coachTip: 'El rey viaja dos casillas hacia el ala de dama (c1) y la torre a1 pasa a d1.',
        initialFen: 'r3kbnr/pppqpppp/2np4/1b6/4P3/2NP1N2/PPPQBPPP/R3K2R w KQkq - 6 6',
        targetPieceSquare: 'e1',
        goalSquares: ['c1'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Enroque largo completado! Tu rey está resguardado.',
        profeProCorrection: 'Mueve el rey dos casillas a la izquierda hacia c1.',
      },
    ],
    rewardXp: 140,
    rewardCoins: 140,
  },

  // ==================== 11. LA PROMOCIÓN ====================
  {
    id: 'promotion',
    order: 11,
    pieceName: 'La Promoción',
    pieceSymbol: '👑',
    kidsName: '¡La Gran Coronación!',
    kidsIcon: '👑',
    themeColor: '#7C3AED',
    introTitle: '¡El Peón se Convierte en Dama!',
    introStory:
      'Cuando un valiente peón cruza todo el tablero y llega a la última fila, ¡se corona y se transforma en Dama, Torre, Alfil o Caballo!',
    movementRules:
      'Avanza el peón a la 8ª fila para transformarlo en la pieza que elijas (normalmente la Dama).',
    demonstrationFen: '8/4P3/8/8/8/8/8/4K2k w - - 0 1',
    realPieceComparison: {
      kidsName: 'Corona Mágica 👑',
      kidsEmoji: '👑',
      classicName: 'Promoción (=Q)',
      classicSymbol: '=Q',
      explanation:
        'En notación se indica con el signo igual y la pieza elegida, ej. e8=Q.',
    },
    exercises: [
      {
        id: 'promotion_ex1',
        title: '¡Coronación Inminente!',
        instructions: 'Avanza el peón de e7 a e8 para coronar una poderosa Dama.',
        coachTip: 'Un solo paso separa a tu peón de convertirse en la pieza más poderosa.',
        initialFen: '8/4P3/8/8/8/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'e7',
        goalSquares: ['e8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡CORONASTE DAMA! Tu peón se ha convertido en la reina del tablero.',
        profeProCorrection: 'Avanza el peón a la última fila en e8.',
      },
      {
        id: 'promotion_ex2',
        title: 'La Carrera de Peones',
        instructions: 'Avanza el peón libre de b7 a b8 para asegurar la victoria.',
        coachTip: 'Ninguna pieza rival puede alcanzar a tu peón imparable.',
        initialFen: '8/1P6/8/8/8/8/8/4K2k w - - 0 1',
        targetPieceSquare: 'b7',
        goalSquares: ['b8'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Coronación magistral! El tablero es tuyo.',
        profeProCorrection: 'Avanza el peón a b8.',
      },
    ],
    rewardXp: 150,
    rewardCoins: 150,
  },

  // ==================== 12. MI PRIMERA PARTIDA ====================
  {
    id: 'first_game',
    order: 12,
    pieceName: 'Mi Primera Partida',
    pieceSymbol: '🎓',
    kidsName: 'Graduación de Campeón',
    kidsIcon: '🎓',
    themeColor: '#D97706',
    introTitle: '¡Listo para Jugar y Triunfar!',
    introStory:
      '¡Enhorabuena! Conoces todas las piezas, los jaques, el enroque y la coronación. ¡Es hora de dominar el centro y ganar!',
    movementRules:
      'Aplica los 3 principios de apertura: 1. Controla el centro. 2. Desarrolla caballos y alfiles. 3. Protege a tu Rey.',
    demonstrationFen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
    realPieceComparison: {
      kidsName: 'Diploma Maestro 🎓',
      kidsEmoji: '🎓',
      classicName: 'Graduación AjedrezPro',
      classicSymbol: '🏆',
      explanation:
        '¡Has completado los 12 fundamentos de la Escuela AjedrezPro! Listo para torneos.',
    },
    exercises: [
      {
        id: 'first_game_ex1',
        title: 'Dominio Central',
        instructions: 'Comienza tu partida jugando el peón de rey dos casillas a e4.',
        coachTip: 'e4 controla el centro del tablero y abre paso para tu Dama y Alfil.',
        initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        targetPieceSquare: 'e2',
        goalSquares: ['e4'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Brillante! Has dado el primer paso maestro en tu carrera de ajedrez.',
        profeProCorrection: 'Mueve el peón de e2 a e4 para abrir el juego.',
      },
      {
        id: 'first_game_ex2',
        title: 'Desarrollo de Caballos',
        instructions: 'Desarrolla el caballo blanco a f3 apuntando al centro.',
        coachTip: 'Los caballos van hacia el centro para maximizar su radio de acción.',
        initialFen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
        targetPieceSquare: 'g1',
        goalSquares: ['f3'],
        optimalMoves: 1,
        maxAllowedMoves: 1,
        profeProPraise: '¡Desarrollo ejemplar! Tu ejército está listo para cualquier reto.',
        profeProCorrection: 'Mueve el caballo a f3.',
      },
    ],
    rewardXp: 200,
    rewardCoins: 200,
    rewardItemId: 'piece_kids_classic',
  },
] as const;

export function getLessonById(id: string): SchoolLesson | undefined {
  return SCHOOL_LESSONS.find((l) => l.id === id);
}
